### ISSUE TITLE
POST & CRUD services

### ISSUE THREAD

**Issue by bocytko** [zalando/restful-api-guidelines#114] opened 2016-07-26 09:52 UTC
I have seen attempts to implement idempotency with POST for simple CRUD services. Would be nice if the guidelines are more clear on this use case. An approach for handling ids should be suggested for services that would like to manage their own number ranges for ids (like another endpoint for id generation).

[POST](http://zalando.github.io/restful-api-guidelines/http/Http.html#post) could also mention that returning `409 Conflict` to realize idempotency is discouraged and a bad practice.

**Comment by whiskeysierra** [comment] 2016-07-26 13:35
One question in regards to this that I still haven't found an answer for: 
Assuming that we leave id generation to the clients, how does a client distinguishes between the two reasons when a `PUT` + `If-None-Match *` (only apply the change if the resource doesn't exist yet) request failed because the resource already exists:

1. Because the client retried an earlier, failed request (e.g. timeout)
2. Another client generated the same identifier and it's now taken

**Comment by ePaul** [comment] 2016-07-26 14:10
@whiskeysierra requesting the resource with GET and see if it's the one we want?

But generally, ID-generation by clients does only work reliably if either

* there is just one client (or one entity generating IDs), or
* there is some namespacing going on, i.e. each client generates its IDs in a way that they don't conflict with each other (which could be enforced by the server, or just rely on convention), or
* clients generate UUIDs or something similar which makes conflicts highly improbable.

**Comment by bocytko** [comment] 2016-07-26 21:38
@whiskeysierra wouldn't the entity owner be enough to distinguish both cases?

@ePaul 

> there is just one client (or one entity generating IDs)

IMHO it's too restrictive. Today there is one client, tomorrow we have more.

> there is some namespacing going on, i.e. each client generates its IDs in a way that they don't conflict with each other (which could be enforced by the server, or just rely on convention), or

Ideally, clients manage their own namespace and the system uses a compound key (tenant_id, id) to identify generated entities.

> clients generate UUIDs or something similar which makes conflicts highly improbable

If the backend is using global IDs (and is not multi-tenant), then clients should use UUIDs as client-generated IDs.

When the server decides to manage number ranges for the clients, then the server should offer endpoints where clients can get a unique number from and use it when creating resources via `PUT`.

**Comment by whiskeysierra** [comment] 2016-07-27 07:19
> POST could also mention that returning 409 Conflict to realize idempotency is discouraged and a bad practice.

Can you elaborate?

**Comment by tkrop** [comment] 2016-07-27 07:24
@bocytko Willi and I have talked a lot about this topic before deciding about a first approach for the customs API. We agreed, that the problem is the question how to manage the id-space as @ePaul  mentioned.

In my opinion any approach to explain customers, how they are responsible for correct ID creation or supporting calls via GET is difficult and leads to a number of possible failure scenarios. This makes  `PUT` + `If-None-Match: *` a less preferable option.

On the other hand I think it is easier to handle and to explain, that a POST request can contain a foreign id-space bound unique key, that can be used to detect idempotent operations reliably. This has the advantage that id generation is still responsibility of the server and is not exposed to the clients, which I would prefer as a best practice.

@whiskeysierra and I had although an extended discussion about which code to return, i.g. `200` or `409` on a duplicate request. From the perspective of an client both must result in the same behavior, but in my opinion `409` should be used for a different semantic, e.g. when there is a semantic difference in the two received requests - if this is checked at all. Using code `200` as duplicate and maybe `201` for the first request would have the advantage of allowing simpler and more unified client side handling. Anyhow, this are semantic peculiarities that in my  opinion do not really matter.

@bocytko can you please argue why you would suggest using `409` for the duplicate request to be bad practice?

**Comment by bocytko** [comment] 2016-07-27 10:12
> On the other hand I think it is easier to handle and to explain, that a POST request can contain a foreign id-space bound unique key, that can be used to detect idempotent operations reliably.
> This has the advantage that id generation is still responsibility of the server and is not exposed to the clients, which I would prefer as a best practice.

For support of foreign ids, you can offer:

- `PUT /entities/{tenant}/{foreign-id}` (+GET) - foreign id can be a uuid (but it's not required).
- `/entities/{id}` - for global access / uuid must be used if creation via PUT is required.

You can skip the latter if you don't need globally unique ids.

> can you please argue why you would suggest using 409 for the duplicate request to be bad practice?

My argument is about `POST + 409`.
`POST` does not guarantee idempotency and always creates new entities (or triggers computation, ...). As I understand the guidelines today, `POST` has to be used only if other methods cannot be used to implement the use case. A combination of POST + PUT can be offered as follows:

1. `POST /entities` - returns a location of the new entity, returns `200/1` or `509` (never a `409`)
2. `PUT /entities/{id}` - creates the entity and offers idempotency
  - `200/1` for retry/success,
  - `400` for functional errors,
  - `409` if id is being reused.

Point 1 is only needed if we support server generated ids. (alternatively even another service for unique id generation)
If PUT-only is supported (client-generated ids), uuids are a must.

**Comment by whiskeysierra** [comment] 2016-07-27 11:03
> PUT /entities/{id} - creates the entity and offers idempotency
> 200/1 for retry/success,
> 400 for functional errors,
> 409 if id is being reused.

How do you differentiate between 201 retry and 409 reused?

**Comment by bocytko** [comment] 2016-07-27 14:26
> How do you differentiate between 201 retry and 409 reused?

Two calls with same id, but different content (entities differ from each other).

**Comment by whiskeysierra** [comment] 2016-07-27 14:29
What if it was a retry but it was already modified in between. E.g.
Timestamps added etc. That's not really straightforward to implement.

**Comment by ePaul** [comment] 2016-08-16 12:41
POST vs. PUT will be clarified with #88, more guidance will be in a separate Micro Service Guidelines document (first draft will be done by Christoph).

**Closed by ePaul** 2016-08-16 12:41 UTC
