### ISSUE TITLE
Improve status code guidance

### ISSUE THREAD

**Issue by dehora** [zalando/restful-api-guidelines#233] opened 2017-05-12 09:16 UTC
The guidance ["Use Specific HTTP Status Codes"](https://github.com/zalando/restful-api-guidelines/blob/master/http/Http.md#-bookmust--use-specific-http-status-codes) could be improved and needs some editing:

- The three bullet points should be their own guidance (putting a should keyword inside a must titled guideline is confusing). It's easier to read for busy people.

- The guidance fails to mention that codes are designed around top level responses classes that user agents (API clients) should always be able to do something with and that codes are generic like methods.  For example, getting a 201 from a DELETE is not wrong, but the table indicates otherwise.

- The titled guidance is ok for API designers but not for API customers. It biases customers to only expect specific codes instead of handling the code class in a forward compatible manner (this comes up frequently with 200, 202, 201 and 204 for example). Technically speaking, HTTP Clients that don't understand a particular response code in the response class `R` are required to treat it as the `R00` code, API clients should not be an exception to this. 

- 207 is mandated but not called out as an exception that breaks with HTTP. 2xx is the success range but 207 is a must level guideline elsewhere to signal partial failures, which means API clients have to always check and can't dispatch on the top level code.

- It's not clear if the tables are explanatory or are meant as guidance (eg prefer to use these codes with these methods). If they are explanatory, they can be replaced with a link to wikipedia's page. At the very least the method column should be removed. It's probably with the intent of being helpful but it's creating a private subset of HTTP.

**Comment by tkrop** [comment] 2017-05-29 14:39
> The three bullet points should be their own guidance (putting a should keyword inside a must titled guideline is confusing). It's easier to read for busy people.

@dehora I'm not sure, that this improves the guidance. It is true that the HTTP section contains many more rules than it reveals by section titles, but I do not think that it would improve readability of the document to factor them out as first level rules. The current structure is designed around *HTTP verbs* and certain *use/error cases*.

> The guidance fails to mention that codes are designed around top level responses classes that user agents (API clients) should always be able to do something with and that codes are generic like methods. For example, getting a 201 from a DELETE is not wrong, but the table indicates otherwise.

@dehora Agreed, the guidance is neglecting this because it states: *You should use the most specific HTTP status code for your concrete resource request processing status or error situation.* In addition, it is biased in the way that it expresses what you should use as combinations instead of what is allowed to be used together.

> The titled guidance is ok for API designers but not for API customers. It biases customers to only expect specific codes instead of handling the code class in a forward compatible manner (this comes up frequently with 200, 202, 201 and 204 for example). Technically speaking, HTTP Clients that don't understand a particular response code in the response class R are required to treat it as the R00 code, API clients should not be an exception to this.

@dehora true, the rule is missing the clients perspective and thus may lead to clients that violate the compatibility rule http://zalando.github.io/restful-api-guidelines/compatibility/Compatibility.html#must-prepare-clients-for-compatible-api-extensions-the-robustness-principle.

Agreed, we should add this compatibility guide in http://zalando.github.io/restful-api-guidelines/http/Http.html#must-use-specific-http-status-codes again with the reference to the compatibility section.

> 207 is mandated but not called out as an exception that breaks with HTTP. 2xx is the success range but 207 is a must level guideline elsewhere to signal partial failures, which means API clients have to always check and can't dispatch on the top level code.

@dehora yes, that is why we added this section to absolutely clarify this expected behavior and handling. Do we have to add something to make this more explicit?

> It's not clear if the tables are explanatory or are meant as guidance (eg prefer to use these codes with these methods). If they are explanatory, they can be replaced with a link to wikipedia's page. At the very least the method column should be removed. It's probably with the intent of being helpful but it's creating a private subset of HTTP.

@dehora as guidance.

@dehora can you please prepare pull requests with the changes you like to make to improve the guidance? Than it would be easier to discuss the effect.

**Comment by ePaul** [comment] 2017-06-14 12:44
As we found out in https://github.com/zalando-incubator/zally/issues/374, the current wording of the guideline can be misunderstood.

> * You must not invent new HTTP status codes; only use standardized HTTP status codes and consistent with its intended semantics.
> * You should use the most specific HTTP status code for your concrete resource request processing status or error situation.
> * You should provide good documentation in the API definition when using HTTP status codes that are less commonly used and not listed below.

I thought that the three items are quite clear:

- It does *not* say that you are only allowed to use the listed status codes (just that you should document clearly when you are using a not listed one)
- It says to only use codes defined in RFCs
- It says to follow the semantics given in those RFCs
- It says to use the most specific status code which is applicable to a given situation.

Unfortunately this is not something which is easily checked automatically (with our current AI level).

**Comment by ePaul** [comment] 2017-09-26 12:34
@tfrauenstein updates the guidelines to make the "document if other code" clearer, and also talks with @dehora about his issues.

**Comment by tfrauenstein** [comment] 2017-11-10 08:44
@dehora as discussed, meanwhile there have been some updates for better description of status code handling. Pls. check that your editorial hints are addressed and, if not, create concrete PR such that we can close this issue. Thank you.

**Comment by wakingrufus** [comment] 2018-02-13 14:52
Which status code is recommended for when a submitted resource fails business logic validation? I generally use 422 for this, but I do not see that status code in the table.

**Comment by whiskeysierra** [comment] 2018-02-13 14:54
@wakingrufus We decided against 422 in favor of 400, since 422 is not part of the HTTP RFC but Webdav.

**Closed** 2018-05-02 14:30 UTC
Labels: editorial, guideline-change
