### ISSUE TITLE
Deprecate HAL

### ISSUE THREAD

**Issue by dehora** [zalando/restful-api-guidelines#147] opened 2016-10-24 09:54 UTC
Deprecate HAL from the guidelines and replace it with local guidance designed to work with Open API. 
- since HAL has been subsetted to just links, all it effectively does is tell teams to create an object structure called `_links`. There's no real value in an underscore, we could at this point tell people to create an object called `links` and obtain the same benefits.
- HAL is unfriendly to code generators [1] because it identifies the link using the rel as the key. This result in object structures that are awkward to deal with and drop relations that are unknown at compile time. 

The replacement guidance would (or could) be:
- use `links` to enclose link structures in an array
- define a Link object that contains a `rel` and `href` fields

---

[1] For example using vanilla swagger you get an enclosing links object something like this

``` java
public class PaginationLinks   {
  private PaginationLink prev = null;
  private PaginationLink next = null;
  ...
}

public class PaginationLink   {
  private String href = null;
  ...
}
```

Note the rels are mapped to field names in `PaginationLinks`. That means new rels will be dropped by clients meaning higher level code can't use them without recompilation. The [Hypermedia](http://zalando.github.io/restful-api-guidelines/hyper-media/Hypermedia.html) guidance points out that keys are fields in its recommended object definitions:

``` md
# keys are link relations
```

But it doesn't point out new rels will be dropped on the floor. Regardless of your position on the guidelines aiming for Richardson L2 maturity, using keys this way for data that is intended to be extensible by the server isn't an optimal approach for Open API. 

An alternative model would be: 

``` json
links=[
 {
   "rel": "...",
   "href": "...",
 }
]
```

That results in generated code that carries the `rel` and won't drop new rels sent by the server:

``` java
public class MyCollection   {
  private List<Link> links = null;
  ...
}

public class Link   {
  private String rel = null;
  private String href = null;
  ...
}
```

It's closer in style to an `a` tag in html or rss/atom links.  The downside is that finding a particular rel requires an iteration and is O(N). The argument is the number of rels in the loop isn't worth worrying about in general (we're talking single digit list sizes in the vast majority of cases, which is pagination or alternate references), and even it were, it's easy to do a one time pass into a map structure to provide an index.

**Comment by whiskeysierra** [comment] 2016-10-24 10:48
> since HAL has been subsetted to just links

We don't forbid to use `_embedded`, do we?

> There's no real value in an underscore

Well, except that it makes us compliant with the standard.

> HAL is unfriendly to code generators [1] because it identifies the link using the rel as the key. This result in object structures that are awkward to deal with and drop relations that are unknown at compile time.

I disagree. The first problem is the use of a code generator that you can't control. A good generator would treat the `additionalProperties` hint to generate a `Map<String, List<Link>>` (or even `Multimap<String, Link>`, if it supports e.g. Guava). It won't drop unknown relations. It's easy to inspect the set of relations. Checking for existence is easy. It also has the natural support for fast lookups.

> But it doesn't point out new rels will be dropped on the floor. 

That has nothing to do with the specification of the API but how a client chooses to implement it. Using a code generator is a choice that comes with drawbacks, clients have to be aware of that.

> Regardless of your position on the guidelines aiming for Richardson L2 maturity, using keys this way for data that is intended to be extensible by the server isn't an optimal approach for Open API.

Why?

> An alternative model would be:

Clients will almost exclusively access links by relation, so a key-based lookup is the natural choice.

My 2c

**Comment by dehora** [comment] 2016-10-24 11:26
> I disagree. The first problem is the use of a code generator that you can't control. A good generator...

I've been using swagger's own code generator with defaults. With the bare structures in the guidelines it extends `HashMap<String, List>`. That's maybe tolerable, depending on whether you think extending HashMap is good design (I don't) or you're happy with the types being erased (I'm not). 

Otoh if you _define_ the rel links as opposed to document them you can end up with non-extensible code:

```yaml
  Links:
    description: contains links 
    type: object
    properties:
      prev:
        $ref: '#/definitions/Link'
      next:
        $ref: '#/definitions/Link' 
```

The problem here is that the output is also valid according to HAL - the guidelines don't say must use the definition (eg the way we do with Money or Porblem), just must use HAL. It's left up to service designers to get it right instead of providing clear constraints.

> Well, except that it makes us compliant with the standard.

It's a draft RFC that's not on the standards track, and that's had no significant updates in some years. I don't find a standards argument compelling. At a de-facto level it's clear to me how many people are using it to spec and not profiling it (eg ignoring the fact that it's a media type and not a structured json extension). That should raise questions

> That has nothing to do with the specification of the API but how a client chooses to implement it.

Again, this is swagger's own codegen tool. If we're saying it's doing a bad job, we need to call that out in the guidelines or require using a definition that works well with the existing toolchain. (It's not imo realistic to advocate Open API and ignore the tooling around it.) 

> Why?

Because there's potential to drop data when there's no compelling reason to drop it, unless you don't define the actual rels. That's at best awkward, at worst it means servers and clients need to coordinate upgrades to pick up new rel types because the server has encoded the HAL syntax in a particular way.

**Comment by dehora** [comment] 2016-10-24 11:31
> We don't forbid to use _embedded, do we?

Good question - we don't I think As an aside I wonder if `_embedded` interact properly with [Filtered](http://zalando.github.io/restful-api-guidelines/performance/Performance.html#filtered).

**Comment by whiskeysierra** [comment] 2016-10-24 13:25
> I've been using swagger's own code generator with defaults. With the bare structures in the guidelines it extends HashMap<String, List>.

That's a sign of a generator that I would not consider to be production ready. Using HashMap as a field type and raw collections is beyond smelly.

> Again, this is swagger's own codegen tool. If we're saying it's doing a bad job, we need to call that out in the guidelines

Agree, 100%. If the previous example is what the generator produces it's worth being used. Personally I don't use code generation with swagger ever, because of problems like this. And in addition I don't like that fact that it generates a complete model, i.e. with all the properties. I like to define the subset of the API that I actually care about.

> require using a definition that works well with the existing toolchain

I read that as *implementation-driven interface design* and I reject that, with a passion.

> It's not imo realistic to advocate Open API and ignore the tooling around it.

I never used a single OpenAPI tool and I'm quite happy with it so far. Defining my model classes with Lombok (e.g.) is as simple as code gets. Testing needs to be done anyway, so I don't see the point in generating that code.

> Because there's potential to drop data when there's no compelling reason to drop it, unless you don't define the actual rels. That's at best awkward, at worst it means servers and clients need to coordinate upgrades to pick up new rel types because the server has encoded the HAL syntax in a particular way.

I don't really see the problem. If the client doesn't care about a relation it's fine to ignore it. If the server sends a new link relation that is unknown to clients it's ok for them to ignore it. If the client wants to handle it it needs to be changed. I don't see a way around that.

I've yet to encounter a use case where a client would generically read and interpret all link relations. Have you?

**Comment by dehora** [comment] 2016-10-25 09:45
> That's a sign of a generator that I would not consider to be production ready.

To be clear here, we're effectively saying swagger's own generator isn't production ready.

**Comment by whiskeysierra** [comment] 2016-10-25 10:01
> To be clear here, we're effectively saying swagger's own generator isn't production ready.

As long as their code generator uses `HashMap` and raw types, then **yes**. I wouldn't consider using that in production.

> The client can't care about the relation, because under certain circumstances; it won't be marshalled at all. I think we're talking past each other.

Yes we are. My approach is always to write the code myself in which case I (as a client) have the full control over which link relations I care about and therefore which ones I represent in code. If I use the specification as an input for a code generator and that specification is incomplete I don't have the power, obviously.

> Yes, paginators, and discovery.

Pagination uses a strict set of link relations: `next` and `prev` and potentially also `first` and `last`. What's the use case for discovery? I can't think of a client that *discovers* new links relations *automagically* and just does the right thing.

> But with the current model effectively steering people away from sane use of links it's self-fulfilling.

I don't see how we're steering people away from links. We should be steering them away from broken code generators, imho.

**Comment by dehora** [comment] 2016-10-25 10:07
> Pagination uses a strict set of link relations

Again, this isn't the point. The link relations that are not in the documentation in certain circumstances for certain API definitions that are technically correct will get dropped on the floor - the example is above. The fact that you develop in a certain way, doesn't make that vanish.

> We should be steering them away from broken code generators, imho.

I'm not arguing against that. But in the meantime, it's possible to define link constructs that avoid the problem :) Especially given we're using a tiny subset of the HAL spec.

**Comment by whiskeysierra** [comment] 2016-10-25 10:13
> The link relations that are not in the documentation in certain circumstances for certain API definitions that are technically correct will get dropped on the floor

Why don't we tackle the problem there? If the API provider didn't declare the links correctly, why should clients rely on them? If everybody would declare them correctly, there wouldn't be a problem, would there?

> But in the meantime, it's possible to define link constructs that avoid the problem

Again, to me this is *implementation-driven interface design*. The link structure doesn't need to be fixed, the code generator does.

**Comment by dehora** [comment] 2016-10-25 10:18
> I vaguely remember that we wanted to give some guidance about embedding?

@ePaul right, sounds familiarish. If we wanted to give guidance, imo it'd be worth cross-referencing with the filter section.  @whiskeysierra what do you think?

**Comment by ePaul** [comment] 2016-10-25 10:26
From my experience, using relation names as keys works quite well with code generation (using swagger-codegen), as long as you don't have overly long or complicated relation names (e.g. you don't want to have a HTTP URL as a relation name).

Of course, I must confess that I never had the need for clients to receive links with relation types they didn't know before, therefore we didn't define them with `additionalProperties`, but just defined (and used) the links which were known at API design time.

I think there is some value of being compatible to HAL, even if we don't use the full standard.

**Comment by whiskeysierra** [comment] 2016-10-25 11:02
> I vaguely remember that we wanted to give some guidance about embedding? I don't find it in the issue list, though.

https://github.com/zalando/restful-api-guidelines/pull/138 It's merged already.

> If we wanted to give guidance, imo it'd be worth cross-referencing with the filter section.

Yes, those sections should be linked, since they both touch HAL. They sit directly next to each other though.

> (e.g. you don't want to have a HTTP URL as a relation name)

Which we have (or had?) as a rule.

**Comment by fmueller** [comment] 2016-11-04 09:44
@whiskeysierra @dehora After this long discussion, can you identify action items for guideline changes / adjustments?

**Comment by ePaul** [comment] 2016-11-04 18:34
> > (e.g. you don't want to have a HTTP URL as a relation name)
> 
> Which we have (or had?) as a rule.

My team had some bad experiences with HTTP URLs as relation names. I just looked into the guidelines – we didn't actually prescribe the use of URLs for custom relations, and I would recommend against this.

**Comment by whiskeysierra** [comment] 2016-11-04 18:43
Can you share some more details about your bad experience?

**Comment by ePaul** [comment] 2016-11-06 03:15
Basically, swagger-codegen created method names based on the URLs, which were (caused by a stupid choice of URL) longer than my screen width. (I can look up an example in the history of one of our projects tomorrow or on Tuesday.)
Of course, this is only a problem if you are defining the interesting link relations in your API definition, not if you hide them via `additionalProperties` (producing a map) like in the guidelines example.

I also guess for manually built DTOs you simply can use a short name and some annotation for your JSON-mapper with the long URL, but I like my code generation (as it helps to ensure the implementation and API definition fit together).

**Comment by tfrauenstein** [comment] 2016-11-19 14:45
👍 I also agree

**Comment by fmueller** [comment] 2016-11-22 13:38
With whom @tfrauenstein? We assume you mean @codekultur 

As agreed in todays guild meetup we close this issue.

**Closed by fmueller** 2016-11-22 13:38 UTC
Labels: discussion, guideline-change
