### ISSUE TITLE
Anchors don't work properly

### ISSUE THREAD

**Issue by nsorger** [zalando/restful-api-guidelines#149] opened 2016-11-01 10:21 UTC
I can't link to specific sub-sections using the anchor tag anymore.
Example:
http://zalando.github.io/restful-api-guidelines/common-data-objects/CommonDataObjects.html#must-use-common-error-return-objects doesn't bring me to the respective sub-section.

I also don't see the little "anchor" symbol next to headlines/sub headlines

**Comment by ePaul** [comment] 2016-11-08 14:13
This section was renamed (http://zalando.github.io/restful-api-guidelines/common-data-objects/CommonDataObjects.html#must-use-problem-json). We should see if we can check the internal links during the build process.

But the anchor symbol missing is a new problem, likely introduced by #148. Willi will have a look at this.

**Comment by ePaul** [comment] 2016-11-22 13:50
The missing anchor symbol is possibly caused by incompatible library upgrades, and thus could possibly be fixed by upgrading to Gitbook 3 (#106).

**Comment by fmueller** [comment] 2016-12-09 09:42
They still don't work. I investigate.

**Comment by ePaul** [comment] 2017-02-14 13:35
Depends on Gitbook update, which breaks other things. Therefore decided not to do this now.

**Closed by ePaul** 2017-02-14 13:35 UTC
Labels: bug, editorial, wontfix
