### ISSUE TITLE
Make guideline for links more liberal

### ISSUE THREAD

**Issue by fmueller** [zalando/restful-api-guidelines#199] opened 2017-03-06 16:11 UTC
Currently we define in our guidelines to place all links in `_links` field which also has to be an array. This adds quite a lot of boilerplate to json payloads. And we separate metadata like links from actual context they are part of. We do this - I guess - for more generic client implementations. On the other hand we don't believe in generic clients which is one of our arguments against HATEOAS.

I propose to be more liberal with links:
- stick to Link object in our guidelines
- links can be placed anywhere, at best in their context

**Comment by dehora** [comment] 2017-03-06 16:32
> Currently we define in our guidelines to place all links in _links field which also has to be an array.

According to [Must: Use a well-defined subset of HAL](http://zalando.github.io/restful-api-guidelines/hyper-media/Hypermedia.html#must-use-a-welldefined-subset-of-hal) and the examples there,

- it's an object: 

```yaml
Links:
  type: object
```

- links can (must) live anywhere:

> Clients and Servers are required to support _links with its href and rel attributes, not only at the root level but also in nested objects.


It sounds like you're asking for fields that can have link objects as values. What's wrong with using `_links` at any level? I'm not convinced about HAL but the guild is (see #147) and allowing links anywhere seems to pretty much defeat the point of using it.

**Comment by fmueller** [comment] 2017-03-06 16:36
Sorry for misreading this. Right, _links is an object. What's the benefit of wrapping links always inside _links? I only see the 'generic client' argument here and this should not be used by us for this since we used it in past to discourage HATEOAS. You see my point?

Btw: We had a big talk in last API guild meetup about some cons of HAL.

**Comment by ePaul** [comment] 2017-03-06 18:06
> On the other hand we don't believe in generic clients which is one of our arguments against HATEOAS.

Just for the record, I think a schema-aware semi-generic client (like what was presented in the last meeting – sorry that we can't share the details publicly) could use links in a HATEOASy way even if they are not in a `_links` object. (I'll have to work out whether this can be done with OpenAPI 3.0's new `links` feature or if it needs an extension.)

> What's the benefit of wrapping links always inside _links?

Our current use of `_links` already deviates from HAL (`_links` is allowed just at top level for HAL, but also in nested objects for us), just sharing parts of the syntax with it. So it allows having a link nested in the correct part of your response (or less often request), but with some syntactic overhead.

The `_links` object has the advantage of making the link relation type explicit, instead of hiding it in a description of a property.

**Comment by tkrop** [comment] 2017-03-07 08:20
The Ideas are not that difficult to share - e.g. Nokias Here Places API is public:

https://developer.here.com/rest-apis/documentation/places/topics/hypermedia-links.html
https://developer.here.com/rest-apis/documentation/places/topics_api/object-link.html

The main idea is, that not using HAL and restrict representation to `_links` enables an API to make use of a much richer set of flow controls. Using this technique we could build similar APIs e.g. for controlling payment processes or delivery processes from directly from back-end services through the front-end applications.

**Comment by dehora** [comment] 2017-03-07 16:29
> What's the benefit of wrapping links always inside _links? 

I don't see any value in in HAL per se, so you probably want to direct that to the guild, who agreed to close #147 and keep it around. 

> I only see  the 'generic client' argument here and this should 
> not be used by us  for this since we used it in past to discourage 
> HATEOAS. 

I think this is incidental. Well defined links make as much sense as well defined dates; but that isn't necessarily an argument for only putting links in a `_links` object.

The `_links` constraint might have been needed for HAL to work as a media type specification, but it's not needed for APIs predicated on these guidelines:

1. The requirement to use Open API and having a `Link` definition cover what's needed to describe _any_ field as a having a URL/I.

1. The `Link` definition allows clients that want to handle links uniformly to do so (you don't need full blown state representation to justify this, it's useful for basic stuff like rendering links in a UI and pagination).

1. There's no issue in allowing a field to have a direct link because links can (and must be) fully described using the `Link` definition type.  For example, there's no compelling need to wrap someone's avatar link in a `_links` object instead of having an `avatar` field whose  direct value is a `Link`. 

So I don't seen an issue in relaxing where links can exist in documents. The guidelines do not require all date fields to live in a `_dates` object and we've somehow survived. But to do so does means dropping the must level requirement around HAL to make the guidelines coherent.

> _links is allowed just at top level for HAL, but also in nested objects for us,

I skimmed through HAL again. Just to be clear, I don't see that constraint - top level objects must be resource objects, but that doesn't mean other nested objects can't be resource objects.

**Comment by ePaul** [comment] 2017-03-07 17:18
@whiskeysierra Do you care to comment here?

**Comment by meshcalero** [comment] 2017-03-07 19:25
@tkrop You'll find a more detailed description of the hypertext control model behind HERE's Places API at http://blog.meshcaline.org/basics/#hypertextcontrols. It differs in some details -- the doc was written long after the API launch and modified some minor aspects we would have done differently if we could have started from scratch.

@dehora I would disagree with you statement that HAL supports _links in nested objects. HAL says that a HAL document contains a resource which contains links, embedded resources and resource state ("plain old JSON properties"). HAL doesn't say anything about how to model the resource state, and as such also doesn't prevent you from placing a objects with attributes called _links there, but those are then not covered by the HAL specification and not part of the standard processing model for HAL documents. For that I'd say you would have to place them in the collection of embedded resources.

**Comment by dehora** [comment] 2017-03-07 20:36
> I would disagree with your statement that HAL supports _links in nested objects of the state. 

Right; I still can't see where that's disallowed in draft8 (as opposed to allowed) so it comes down to interpretation or just looking at the examples as being the spec. I suspect the problem is HAL is underspecified here.

**Comment by tkrop** [comment] 2017-07-06 15:02
@meshcalero Do we need to address something more here?

Should have been fixed by #246 and #256 if not counting the bugfixes and ubdates from #263 and #264.

**Closed** 2017-08-01 13:21 UTC
Labels: discussion, guideline-change
